Repository RobinTail/express-zod-api, pull requests merged in 2023-12, with the labels that each got.

#1343 Fix: supporting primitive values for logging metadata
  src/logger.ts
  src/server.ts
  tests/unit/logger.spec.ts
Labels: enhancement, prevention

#1346 Supporting primitive values for logging metadata, port for v14
  src/logger.ts
  src/server.ts
  tests/unit/logger.spec.ts
Labels: refactoring, prevention

#1347 Restoring `createLogger` in v15
  CHANGELOG.md
  src/index.ts
  src/logger.ts
  src/server.ts
  tests/unit/__snapshots__/index.spec.ts.snap
  tests/unit/logger.spec.ts
Labels: refactoring

#1348 Hotfix: handling empty object logging
  CHANGELOG.md
  src/logger.ts
  tests/unit/logger.spec.ts
Labels: bug

#1301 `v15` is for Vika
  .github/workflows/codeql-analysis.yml
  .github/workflows/node.js.yml
  .github/workflows/swagger.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  example/config.ts
  example/example.swagger.yaml
  package.json
  src/common-helpers.ts
  src/config-type.ts
  src/endpoint.ts
  src/endpoints-factory.ts
  src/errors.ts
  src/index.ts
  src/logger.ts
  src/middleware.ts
  src/mock.ts
  src/peer-helpers.ts
  src/result-handler.ts
  src/routing.ts
  src/server.ts
  src/startup-logo.ts
  src/testing.ts
  src/upload-schema.ts
  tests/system/system.spec.ts
  tests/unit/__snapshots__/index.spec.ts.snap
  tests/unit/common-helpers.spec.ts
  tests/unit/config-type.spec.ts
  tests/unit/documentation.spec.ts
  tests/unit/endpoint.spec.ts
  tests/unit/errors.spec.ts
  tests/unit/logger.spec.ts
  tests/unit/mock.spec.ts
  tests/unit/peer-helpers.spec.ts
  tests/unit/routing.spec.ts
  tests/unit/server.spec.ts
  tests/unit/testing.spec.ts
  tests/vitest/.gitignore
  tests/vitest/compat.spec.ts
  tests/vitest/package.json
  tests/vitest/tsconfig.json
  tools/esm-test.ts
  tools/integration-test.ts
  tools/startup-logo.ts
  tsconfig.json
  yarn.lock
Labels: dependencies, coverage, refactoring, CI/CD, breaking, dedication

#1350 Replacing `.npmignore` with `files` in `package.json`
  .npmignore
  package.json
Labels: refactoring, CI/CD

#1353 Ref: cleanup redundancies
  .eslintrc.json
  .gitignore
  .prettierignore
  tests/vitest/.gitignore
  tools/esm-test.ts
Labels: refactoring

#1355 Ref: Stable `package.json` for integration tests
  .gitignore
  .prettierignore
  tests/esm/dist.package.json
  tests/esm/package.json
  tests/integration/dist.package.json
  tests/integration/package.json
  tests/vitest/package.json
  tools/esm-test.ts
  tools/integration-test.ts
  tsconfig.json
Labels: dependencies, refactoring, CI/CD

#1356 Ref: dedicated environment for issue #952 test
  .gitignore
  .prettierignore
  package.json
  tests/esm/package.json
  tests/integration/package.json
  tests/issue952/package.json
  tests/issue952/tsconfig.json
  tools/integration-test.ts
  tools/issue952-test.ts
Labels: dependencies, refactoring, CI/CD

#1357 CI: Moving build step after unit tests.
  .github/workflows/node.js.yml
Labels: CI/CD

#1358 Ref: making `vitest` compatibility test an integration one
  tests/vitest/compat.spec.ts
  tests/vitest/package.json
Labels: refactoring, CI/CD

#1362 Ref: organizing CI/CD commands
  package.json
Labels: refactoring, CI/CD

#1363 Ref: single dynamic tests making tool.
  package.json
  tools/esm-test.ts
  tools/extract-quick-start.ts
  tools/integration-test.ts
  tools/issue952-test.ts
  tools/make-tests.ts
Labels: refactoring, CI/CD

#1371 Ref: using `node:assert/strict` instead of `if + throw`
  example/endpoints/retrieve-user.ts
  example/endpoints/update-user.ts
  example/middlewares.ts
  src/documentation-helpers.ts
  src/documentation.ts
  src/endpoint.ts
  src/middleware.ts
  src/routing-walker.ts
  tests/system/system.spec.ts
  tests/unit/documentation-helpers.spec.ts
  tests/unit/endpoint.spec.ts
  tests/unit/server.spec.ts
  tests/unit/zts.spec.ts
Labels: refactoring

#1376 Switching to `tsx` for running commands and scripts
  .github/workflows/node.js.yml
  package.json
  tests/esm/quick-start.spec.ts
  tests/integration/quick-start.spec.ts
  tests/system/example.spec.ts
  yarn.lock
Labels: dependencies, CI/CD

#1379 Support Node 20.0.0
  .github/workflows/node.js.yml
  package.json
Labels: dependencies, CI/CD

#1378 Improving startup logo tool
  src/startup-logo.ts
  tests/unit/startup-logo.spec.ts
  tools/startup-logo.ts
Labels: refactoring

#1380 Debug line with build id running
  src/routing.ts
  tsup.config.ts
Labels: CI/CD, prevention

#1381 Improve pascal case in `makeCleanId`
  src/common-helpers.ts
  tests/unit/__snapshots__/common-helpers.spec.ts.snap
  tests/unit/__snapshots__/documentation.spec.ts.snap
  tests/unit/common-helpers.spec.ts
Labels: enhancement

#1382 Pretty formatted Integration (including example)
  README.md
  example/example.client.ts
  example/generate-client.ts
  package.json
  src/index.ts
  src/integration-helpers.ts
  src/integration.ts
  tests/unit/__snapshots__/index.spec.ts.snap
  tests/unit/__snapshots__/integration.spec.ts.snap
  tests/unit/integration.spec.ts
Labels: documentation, dependencies, refactoring, breaking

#1385 Async detached Documentation
  .github/workflows/swagger.yml
  README.md
  example/example.documentation.yaml
  example/generate-documentation.ts
  example/generate-open-api-schema.ts
  package.json
  src/documentation-helpers.ts
  src/documentation.ts
  src/index.ts
  tests/unit/__snapshots__/documentation.spec.ts.snap
  tests/unit/__snapshots__/index.spec.ts.snap
  tests/unit/documentation.spec.ts
Labels: documentation, enhancement, dependencies, refactoring, breaking

#1387 Switching to OAS 3.1
  .github/workflows/swagger.yml
  CHANGELOG.md
  example/example.documentation.yaml
  src/documentation-helpers.ts
  src/documentation.ts
  tests/unit/__snapshots__/documentation-helpers.spec.ts.snap
  tests/unit/__snapshots__/documentation.spec.ts.snap
  tests/unit/documentation-helpers.spec.ts
Labels: enhancement, miracle

#1391 Improving type constraints in documentation helpers
  src/documentation-helpers.ts
Labels: refactoring, prevention

#1394 Introducing issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: documentation

#1395 Introducing contribution guidelines
  CONTRIBUTING.md
  README.md
Labels: documentation

#1407 Upgrading all dependencies.
  yarn.lock
Labels: dependencies

#1408 Fixing the Endpoint methods tests naming.
  tests/unit/__snapshots__/endpoint.spec.ts.snap
  tests/unit/endpoint.spec.ts
Labels: refactoring

#1412 Splitting the response types in the generated client
  CHANGELOG.md
  README.md
  src/integration.ts
  tests/unit/__snapshots__/integration.spec.ts.snap
  tests/unit/integration.spec.ts
Labels: enhancement, prevention

#1410 Support connecting express router in app config.
  src/config-type.ts
  src/routing.ts
  tests/unit/config-type.spec.ts
  tests/unit/index.spec.ts
  tests/unit/routing.spec.ts
Labels: enhancement

#1413 Moving `resolveJsonModule` into the package `tsconfig` solely
  tsconfig.base.json
  tsconfig.json
Labels: refactoring, CI/CD

#1415 Ref: `makeCleanId` more generic
  src/common-helpers.ts
  src/documentation-helpers.ts
  src/documentation.ts
  src/integration.ts
  tests/unit/__snapshots__/common-helpers.spec.ts.snap
  tests/unit/common-helpers.spec.ts
Labels: refactoring

#1416 Better component descriptions and naming
  CHANGELOG.md
  README.md
  example/example.documentation.yaml
  src/common-helpers.ts
  src/documentation-helpers.ts
  src/documentation.ts
  tests/unit/__snapshots__/documentation-helpers.spec.ts.snap
  tests/unit/__snapshots__/documentation.spec.ts.snap
  tests/unit/documentation.spec.ts
Labels: enhancement, breaking

#1386 `v16` is for Nina
  .github/workflows/codeql-analysis.yml
  .github/workflows/node.js.yml
  .github/workflows/swagger.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  example/example.client.ts
  example/example.documentation.yaml
  example/generate-client.ts
  example/generate-documentation.ts
  package.json
  src/common-helpers.ts
  src/documentation-helpers.ts
  src/documentation.ts
  src/integration-helpers.ts
  src/integration.ts
  src/startup-logo.ts
  tests/unit/__snapshots__/common-helpers.spec.ts.snap
  tests/unit/__snapshots__/documentation-helpers.spec.ts.snap
  tests/unit/__snapshots__/documentation.spec.ts.snap
  tests/unit/__snapshots__/integration.spec.ts.snap
  tests/unit/common-helpers.spec.ts
  tests/unit/documentation-helpers.spec.ts
  tests/unit/documentation.spec.ts
  tests/unit/integration.spec.ts
  tools/startup-logo.ts
Labels: documentation, enhancement, dependencies, refactoring, breaking, dedication

#1418 Upgrading all dependencies.
  yarn.lock
Labels: dependencies

#1419 Using typescript factory for producing `getStartupLogo`
  src/integration-helpers.ts
  src/integration.ts
  src/startup-logo.ts
  tools/startup-logo.ts
Labels: refactoring

#1420 Third party licenses files
  LICENSE-3RD-PARTY.md
  src/startup-logo.ts
  src/zts-helpers.ts
  src/zts.ts
  tests/unit/zts.spec.ts
  tools/startup-logo.ts
Labels: documentation, refactoring, CI/CD

#1423 Ref: parse when depicting transformation effect
  src/common-helpers.ts
  src/documentation-helpers.ts
  src/zts.ts
Labels: refactoring

#1424 Ref: using schema for `ZodUpload` validation
  src/upload-schema.ts
Labels: refactoring

#1425 Feat: Describing alternative or actual placement of the input security
  example/example.documentation.yaml
  src/documentation-helpers.ts
  src/documentation.ts
  tests/unit/__snapshots__/documentation-helpers.spec.ts.snap
  tests/unit/__snapshots__/documentation.spec.ts.snap
  tests/unit/documentation-helpers.spec.ts
Labels: enhancement

#1427 Ref: better buffer schema for `ez.upload()`
  src/upload-schema.ts
  tests/unit/__snapshots__/upload-schema.spec.ts.snap
  tests/unit/upload-schema.spec.ts
Labels: refactoring

#1428 Ref: easier context access in parsing ZodUpload.
  src/upload-schema.ts
Labels: refactoring

#1430 Ref: Organizing result handlers
  src/endpoint.ts
  src/last-resort.ts
  src/result-handler.ts
  src/server.ts
Labels: refactoring
