Repository RobinTail/express-zod-api, pull requests merged in 2023-02, with the labels that each got.

#806 Fix client-helpers `cleanId` function to properly clean the entire string
  src/client-helpers.ts
  tests/unit/__snapshots__/client.spec.ts.snap
  tests/unit/client.spec.ts
Labels: bug

#815 Fix OpenAPI bearer security
  src/logical-container.ts
  src/open-api-helpers.ts
  tests/unit/__snapshots__/open-api-helpers.spec.ts.snap
  tests/unit/__snapshots__/open-api.spec.ts.snap
  tests/unit/logical-container.spec.ts
  tests/unit/open-api.spec.ts
Labels: bug

#821 Remove request body from `DELETE` operations in OpenAPI spec
  .github/workflows/codeql-analysis.yml
  .github/workflows/node.js.yml
  .github/workflows/swagger.yml
  src/common-helpers.ts
  src/config-type.ts
  src/open-api-helpers.ts
  tests/unit/__snapshots__/common-helpers.spec.ts.snap
  tests/unit/__snapshots__/open-api.spec.ts.snap
  tests/unit/common-helpers.spec.ts
  tests/unit/open-api.spec.ts
Labels: breaking, prevention

#844 Updating coveralls actions
  .github/workflows/node.js.yml
Labels: CI/CD

#845 Adding `operationId` to the documentation
  CHANGELOG.md
  example/example.swagger.yaml
  src/client-helpers.ts
  src/client.ts
  src/common-helpers.ts
  src/open-api.ts
  tests/unit/__snapshots__/open-api.spec.ts.snap
  tests/unit/open-api.spec.ts
Labels: enhancement
