Repository RobinTail/express-zod-api, pull requests merged in 2023-10, with the labels that each got.

#1189 Fixing the bundle exports to allow consumer's declarations
  CHANGELOG.md
  example/example.swagger.yaml
  package.json
  src/endpoint.ts
  src/index.ts
  src/security.ts
  tests/unit/endpoints-factory.spec.ts
Labels: prevention

#1183 Feat: headers as input source
  CHANGELOG.md
  README.md
  dataflow.svg
  src/common-helpers.ts
  src/config-type.ts
  src/documentation-helpers.ts
  tests/unit/__snapshots__/documentation-helpers.spec.ts.snap
  tests/unit/__snapshots__/documentation.spec.ts.snap
  tests/unit/common-helpers.spec.ts
  tests/unit/documentation-helpers.spec.ts
  tests/unit/documentation.spec.ts
Labels: enhancement, refactoring

#1190 Replacing functions with constants
  src/common-helpers.ts
  src/documentation-helpers.ts
  src/logger.ts
  src/metadata.ts
  src/server.ts
Labels: refactoring

#1181 Feat: ability to customize the endpoint operationId in documentation
  src/documentation.ts
  src/endpoint.ts
  src/endpoints-factory.ts
  tests/unit/__snapshots__/documentation.spec.ts.snap
  tests/unit/documentation.spec.ts
Labels: enhancement

#1196 Drop `DependsOnMethodError`
  src/depends-on-method.ts
  src/errors.ts
  src/index.ts
  src/routing-walker.ts
  tests/unit/__snapshots__/depends-on-method.spec.ts.snap
  tests/unit/__snapshots__/index.spec.ts.snap
  tests/unit/__snapshots__/routing.spec.ts.snap
  tests/unit/depends-on-method.spec.ts
  tests/unit/errors.spec.ts
  tests/unit/routing.spec.ts
Labels: refactoring, breaking

#1198 Dropping the `MethodDefinition` and corresponding type argument
  src/endpoint.ts
  src/endpoints-factory.ts
  src/method.ts
Labels: refactoring

#1194 Feat: the `operationId` provider
  CHANGELOG.md
  src/documentation.ts
  src/endpoint.ts
  src/endpoints-factory.ts
  tests/unit/__snapshots__/documentation.spec.ts.snap
  tests/unit/documentation.spec.ts
Labels: enhancement, prevention

#1199 Move syntax sugar
  src/endpoint.ts
  src/endpoints-factory.ts
  tests/unit/endpoint.spec.ts
Labels: refactoring

#1191 Types: reduce usage of `any`
  example/factories.ts
  src/common-helpers.ts
  src/config-type.ts
  src/documentation-helpers.ts
  src/endpoint.ts
  src/endpoints-factory.ts
  src/logger.ts
  src/middleware.ts
  src/result-handler.ts
  src/server.ts
  src/upload-schema.ts
  src/zts.ts
  tests/unit/endpoints-factory.spec.ts
Labels: refactoring, breaking

#1200 Ability to specify multiple server URLs in Documentation
  src/documentation.ts
Labels: enhancement

#1208 Upgrading all dependencies.
  yarn.lock
Labels: dependencies

#1209 Removing `triple-beam`.
  package.json
  src/logger.ts
  yarn.lock
Labels: dependencies, refactoring

#1210 Replacing `ts-node` with `swc-node/register`
  .github/workflows/node.js.yml
  .npmignore
  SECURITY.md
  example/example.swagger.yaml
  example/generate-client.ts
  example/generate-open-api-schema.ts
  jest.config.json
  jest.config.ts
  package.json
  tests/helpers.ts
  tests/system/client.spec.ts
  tests/system/example.spec.ts
  tools/esm-test.ts
  tools/integration-test.ts
  tools/license.ts
  tsconfig.json
  yarn.lock
Labels: dependencies, refactoring, CI/CD, external bug

#1213 Ref: Moving `getRoutePathParams()` helper
  src/common-helpers.ts
  src/documentation-helpers.ts
  tests/unit/common-helpers.spec.ts
  tests/unit/documentation-helpers.spec.ts
Labels: refactoring

#1214 Ref: `LogicalContainer`
  src/logical-container.ts
Labels: refactoring

#1217 Improving types for metadata
  src/metadata.ts
Labels: refactoring

#1218 Improving context type for `SchemaWalker`
  src/documentation-helpers.ts
  src/schema-walker.ts
  src/zts-helpers.ts
  src/zts.ts
  tests/unit/documentation-helpers.spec.ts
Labels: refactoring

#1220 Reduce using `any` in documentation depicters
  src/documentation-helpers.ts
  src/zts.ts
Labels: refactoring

#1221 Replacing type `any` in `arrayResultHandler`
  src/result-handler.ts
Labels: refactoring

#1225 Making `http-errors` a peer dependency.
  CHANGELOG.md
  README.md
  example/endpoints/retrieve-user.ts
  example/endpoints/update-user.ts
  example/middlewares.ts
  package.json
  src/common-helpers.ts
  src/index.ts
  tests/unit/__snapshots__/index.spec.ts.snap
  tests/unit/common-helpers.spec.ts
  tests/unit/result-handler.spec.ts
  yarn.lock
Labels: dependencies, refactoring, breaking

#1227 No `mime` dependency
  example/factories.ts
  package.json
  src/mime.ts
  tests/unit/mime.spec.ts
  yarn.lock
Labels: dependencies, refactoring

#1197 `v14` is for Katie
  .github/workflows/codeql-analysis.yml
  .github/workflows/node.js.yml
  .github/workflows/swagger.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  example/endpoints/retrieve-user.ts
  example/endpoints/update-user.ts
  example/example.swagger.yaml
  example/factories.ts
  example/middlewares.ts
  package.json
  src/common-helpers.ts
  src/config-type.ts
  src/depends-on-method.ts
  src/documentation-helpers.ts
  src/endpoint.ts
  src/endpoints-factory.ts
  src/errors.ts
  src/index.ts
  src/logger.ts
  src/logical-container.ts
  src/metadata.ts
  src/method.ts
  src/middleware.ts
  src/mime.ts
  src/result-handler.ts
  src/routing-walker.ts
  src/schema-walker.ts
  src/server.ts
  src/startup-logo.ts
  src/upload-schema.ts
  src/zts-helpers.ts
  src/zts.ts
  tests/unit/__snapshots__/depends-on-method.spec.ts.snap
  tests/unit/__snapshots__/index.spec.ts.snap
  tests/unit/__snapshots__/routing.spec.ts.snap
  tests/unit/common-helpers.spec.ts
  tests/unit/depends-on-method.spec.ts
  tests/unit/documentation-helpers.spec.ts
  tests/unit/endpoint.spec.ts
  tests/unit/endpoints-factory.spec.ts
  tests/unit/errors.spec.ts
  tests/unit/mime.spec.ts
  tests/unit/result-handler.spec.ts
  tests/unit/routing.spec.ts
  tools/startup-logo.ts
  yarn.lock
Labels: dependencies, refactoring, CI/CD, breaking, dedication

#1229 Better implementation for `compression` and `express-fileupload`
  src/server.ts
  tests/express-mock.ts
  tests/unit/server.spec.ts
Labels: coverage, refactoring

#1230 Ref: DNRY in `server.ts`
  src/server.ts
Labels: refactoring

#1231 Removing redundant `isLoggerConfig` helper.
  src/common-helpers.ts
  src/config-type.ts
  src/server.ts
  tests/unit/__snapshots__/server.spec.ts.snap
  tests/unit/common-helpers.spec.ts
  tests/unit/server.spec.ts
Labels: refactoring

#1253 Upgrading all dependencies.
  yarn.lock
Labels: dependencies

#1257 Fixing tests
  jest.config.json
  package.json
  tests/esm/quick-start.spec.ts
  tests/integration/quick-start.spec.ts
  tests/system/__snapshots__/client.spec.ts.snap
  tests/system/__snapshots__/example.spec.ts.snap
  tests/system/client.spec.ts
  tests/system/example.spec.ts
Labels: coverage, refactoring, CI/CD

#1263 Tests: refactoring and improving performance
  jest.config.json
  package.json
  tests/esm/dist.package.json
  tests/esm/fix-package.ts
  tests/esm/quick-start.spec.ts
  tests/integration/dist.package.json
  tests/integration/fix-package.ts
  tests/integration/quick-start.spec.ts
  tests/system/__snapshots__/client.spec.ts.snap
  tests/system/__snapshots__/example.spec.ts.snap
  tests/system/client.spec.ts
  tests/system/example.spec.ts
  tools/esm-test.ts
  tools/integration-test.ts
Labels: refactoring, CI/CD

#1264 Ref: servers creation and starting
  CHANGELOG.md
  example/example.swagger.yaml
  package.json
  src/server.ts
  tests/esm/quick-start.spec.ts
  tests/express-mock.ts
  tests/helpers.ts
  tests/http-mock.ts
  tests/integration/quick-start.spec.ts
  tests/system/example.spec.ts
  tests/system/system.spec.ts
  tests/unit/documentation.spec.ts
  tests/unit/server.spec.ts
  tools/esm-test.ts
Labels: refactoring
