Repository RobinTail/express-zod-api, pull requests merged in 2024-11, with the labels that each got.

#2135 Switch coverage provider to v8
  package.json
  src/documentation-helpers.ts
  src/graceful-shutdown.ts
  src/migration.ts
  tests/unit/__snapshots__/documentation-helpers.spec.ts.snap
  tests/unit/__snapshots__/zts.spec.ts.snap
  tests/unit/documentation-helpers.spec.ts
  tests/unit/graceful-shutdown.spec.ts
  tests/unit/metadata.spec.ts
  tests/unit/migration.spec.ts
  tests/unit/result-handler.spec.ts
  tests/unit/server-helpers.spec.ts
  tests/unit/zts.spec.ts
  vitest.config.ts
  yarn.lock
Labels: dependencies, coverage, refactoring

#2137 Replacing `originalError` with `cause` on validation errors
  CHANGELOG.md
  README.md
  src/common-helpers.ts
  src/errors.ts
  src/last-resort.ts
  tests/unit/errors.spec.ts
  tests/unit/last-resort.spec.ts
Labels: documentation, refactoring

#2138 Upgrading all dependencies
  yarn.lock
Labels: dependencies

#2139 Drop `originalError` property on validation errors
  CHANGELOG.md
  src/errors.ts
  src/migration.ts
  tests/unit/errors.spec.ts
  tests/unit/migration.spec.ts
Labels: breaking

#2140 Add `cause` to `DocumentationError`
  src/errors.ts
  tests/unit/__snapshots__/documentation-helpers.spec.ts.snap
  tests/unit/__snapshots__/endpoints-factory.spec.ts.snap
  tests/unit/__snapshots__/errors.spec.ts.snap
  tests/unit/documentation-helpers.spec.ts
  tests/unit/endpoints-factory.spec.ts
  tests/unit/errors.spec.ts
  vitest.setup.ts
Labels: enhancement

#2141 Changing the `cause` on `ResultHandlerError`
  src/endpoint.ts
  src/errors.ts
  src/last-resort.ts
  src/result-helpers.ts
  src/server-helpers.ts
  tests/unit/errors.spec.ts
  tests/unit/last-resort.spec.ts
  tests/unit/result-handler.spec.ts
Labels: enhancement, refactoring

#2142 Better error logging
  src/common-helpers.ts
  src/last-resort.ts
  tests/unit/builtin-logger.spec.ts
  tests/unit/endpoint.spec.ts
  tests/unit/last-resort.spec.ts
  tests/unit/result-handler.spec.ts
Labels: enhancement, coverage

#2143 Log all server side errors
  src/common-helpers.ts
  src/result-handler.ts
  tests/unit/common-helpers.spec.ts
  tests/unit/result-handler.spec.ts
Labels: enhancement, coverage

#2145 Serialize errors as objects for vitest snapshots.
  tests/unit/__snapshots__/date-in-schema.spec.ts.snap
  tests/unit/__snapshots__/documentation-helpers.spec.ts.snap
  tests/unit/__snapshots__/endpoints-factory.spec.ts.snap
  tests/unit/__snapshots__/io-schema.spec.ts.snap
  tests/unit/__snapshots__/routing.spec.ts.snap
  vitest.setup.ts
Labels: refactoring

#2144 Generalizing server-side error messages in production mode by default
  CHANGELOG.md
  README.md
  example/example.documentation.yaml
  example/factories.ts
  package.json
  src/common-helpers.ts
  src/endpoint.ts
  src/index.ts
  src/last-resort.ts
  src/result-handler.ts
  src/result-helpers.ts
  src/server-helpers.ts
  src/server.ts
  tests/bench/experiment.bench.ts
  tests/system/__snapshots__/system.spec.ts.snap
  tests/system/system.spec.ts
  tests/unit/__snapshots__/index.spec.ts.snap
  tests/unit/__snapshots__/result-handler.spec.ts.snap
  tests/unit/__snapshots__/result-helpers.spec.ts.snap
  tests/unit/common-helpers.spec.ts
  tests/unit/last-resort.spec.ts
  tests/unit/result-handler.spec.ts
  tests/unit/result-helpers.spec.ts
  tsup.config.ts
  vitest.setup.ts
Labels: documentation, enhancement, coverage, refactoring, prevention, miracle

#2147 Upgrading all dependencies
  yarn.lock
Labels: dependencies

#2148 Drop `getStatusCodeFromError()`
  src/index.ts
  src/migration.ts
  src/result-helpers.ts
  tests/unit/__snapshots__/index.spec.ts.snap
  tests/unit/migration.spec.ts
  tests/unit/result-helpers.spec.ts
Labels: refactoring, breaking

#2150 Making `logger` and its `level` optional
  CHANGELOG.md
  README.md
  example/config.ts
  src/builtin-logger.ts
  src/common-helpers.ts
  src/config-type.ts
  src/result-helpers.ts
  tests/bench/experiment.bench.ts
  tests/unit/builtin-logger.spec.ts
  tests/unit/config-type.spec.ts
  tests/unit/logger-helpers.spec.ts
Labels: enhancement, prevention

#2154 Feat: ability to catch errors in `testMiddleware`
  CHANGELOG.md
  README.md
  src/testing.ts
  tests/unit/testing.spec.ts
Labels: documentation, enhancement

#2155 Upgrading all dependencies
  yarn.lock
Labels: dependencies

#2156 Style: Single statement blocks and empty returns
  eslint.config.js
  example/example.client.ts
  example/factories.ts
  src/common-helpers.ts
  src/documentation-helpers.ts
  src/documentation.ts
  src/endpoint.ts
  src/graceful-shutdown.ts
  src/integration-helpers.ts
  src/integration.ts
  src/logical-container.ts
  src/metadata.ts
  src/middleware.ts
  src/result-helpers.ts
  src/routing-walker.ts
  src/server-helpers.ts
  src/zts-helpers.ts
  src/zts.ts
  tests/bench/experiment.bench.ts
  tests/http-mock.ts
  tests/system/example.spec.ts
  tests/system/system.spec.ts
  tests/unit/__snapshots__/documentation-helpers.spec.ts.snap
  tests/unit/__snapshots__/documentation.spec.ts.snap
  tests/unit/__snapshots__/integration.spec.ts.snap
  tests/unit/date-in-schema.spec.ts
  tests/unit/documentation-helpers.spec.ts
  tests/unit/endpoint.spec.ts
  tests/unit/file-schema.spec.ts
  tests/unit/index.spec.ts
  tools/contributors.ts
Labels: refactoring

#2157 library → framework
  CHANGELOG.md
  README.md
  package.json
  tools/contributors.ts
Labels: documentation, seo

#2158 Readme: fix small `handler` typo
  README.md
Labels: documentation

#2159 Upgrading all dependencies
  package.json
  yarn.lock
Labels: dependencies

#2160 Performance tuning for `getInput()`
  src/common-helpers.ts
  tests/bench/experiment.bench.ts
Labels: refactoring

#2161 Dev: Adjusting package commands
  package.json
  tests/cjs/package.json
  tests/compat/package.json
  tests/esm/package.json
  tests/issue952/package.json
Labels: refactoring, CI/CD

#2129 Making `input` schema optional
  CHANGELOG.md
  README.md
  example/endpoints/list-users.ts
  example/example.documentation.yaml
  example/middlewares.ts
  package.json
  src/common-helpers.ts
  src/endpoints-factory.ts
  src/middleware.ts
  tests/system/system.spec.ts
  tests/unit/depends-on-method.spec.ts
  tests/unit/documentation.spec.ts
  tests/unit/endpoint.spec.ts
  tests/unit/endpoints-factory.spec.ts
  tests/unit/middleware.spec.ts
  tests/unit/routing.spec.ts
  tests/unit/server.spec.ts
  tests/unit/testing.spec.ts
Labels: documentation, coverage, refactoring

#2128 Making `method` and `methods` optional
  CHANGELOG.md
  README.md
  example/endpoints/list-users.ts
  example/endpoints/retrieve-user.ts
  example/endpoints/send-avatar.ts
  example/endpoints/stream-avatar.ts
  example/endpoints/update-user.ts
  src/depends-on-method.ts
  src/documentation.ts
  src/endpoint.ts
  src/endpoints-factory.ts
  src/integration.ts
  src/routing-walker.ts
  src/routing.ts
  tests/system/system.spec.ts
  tests/unit/depends-on-method.spec.ts
  tests/unit/documentation.spec.ts
  tests/unit/endpoint.spec.ts
  tests/unit/endpoints-factory.spec.ts
  tests/unit/routing.spec.ts
  tests/unit/server.spec.ts
  tests/unit/testing.spec.ts
Labels: documentation, enhancement, refactoring, breaking

#2165 Minor: ESLint config syntax
  eslint.config.js
Labels: refactoring

#2162 Deprecating v17
  CHANGELOG.md
  SECURITY.md
Labels: documentation

#2166 Upgrading `vitest` to 2.1.5
  package.json
  vitest.config.ts
  yarn.lock
Labels: dependencies, external bug

#2167 Provide universal `getLogger()` to `beforeRouting`
  CHANGELOG.md
  README.md
  src/config-type.ts
  src/migration.ts
  src/routing.ts
  src/server-helpers.ts
  src/server.ts
  tests/system/system.spec.ts
  tests/unit/migration.spec.ts
  tests/unit/routing.spec.ts
  tests/unit/server-helpers.spec.ts
  tests/unit/server.spec.ts
Labels: documentation, refactoring, breaking

#2169 Revert: `throw` instead of `assert`
  CHANGELOG.md
  eslint.config.js
  src/deep-checks.ts
  src/documentation-helpers.ts
  src/documentation.ts
  src/result-helpers.ts
  src/routing-walker.ts
  tests/bench/experiment.bench.ts
Labels: documentation, refactoring

#2168 Traverse without recursion
  CHANGELOG.md
  eslint.config.js
  src/routing-walker.ts
  tests/bench/experiment.bench.ts
Labels: refactoring

#2171 Performance tuning for `onObject` zts producer
  src/zts.ts
Labels: refactoring

#2172 Addressing performance findings
  eslint.config.js
  src/common-helpers.ts
  src/depends-on-method.ts
  src/documentation.ts
  src/integration-helpers.ts
  src/server.ts
  src/zod-plugin.ts
Labels: enhancement, miracle

#2173 Upgrading all dependencies.
  yarn.lock
Labels: dependencies

#2174 Generalising server type
  src/graceful-shutdown.ts
  src/server.ts
Labels: refactoring

#2179 Client: JSON parser in case of path params
  CHANGELOG.md
  README.md
  example/example.client.ts
  src/integration-helpers.ts
  src/integration.ts
  tests/system/__snapshots__/example.spec.ts.snap
  tests/system/example.spec.ts
  tests/unit/__snapshots__/integration.spec.ts.snap
Labels: bug, documentation

#2175 Universal properties for arrays
  CHANGELOG.md
  README.md
  example/endpoints/send-avatar.ts
  example/endpoints/stream-avatar.ts
  example/factories.ts
  src/api-response.ts
  src/endpoints-factory.ts
  src/migration.ts
  src/result-helpers.ts
  tests/system/system.spec.ts
  tests/unit/documentation.spec.ts
  tests/unit/endpoint.spec.ts
  tests/unit/migration.spec.ts
  tests/unit/routing.spec.ts
  tests/unit/server.spec.ts
Labels: documentation, enhancement, refactoring, breaking

#2184 Upgrading all dependencies
  package.json
  yarn.lock
Labels: dependencies, external bug

#2185 Ease `DocumentationError` constructor
  src/documentation-helpers.ts
  src/documentation.ts
  src/errors.ts
  tests/unit/documentation.spec.ts
  tests/unit/errors.spec.ts
Labels: refactoring, breaking

#2187 Readme: shortening obvious statements.
  README.md
Labels: documentation

#2188 Feat: Nested routes helper
  CHANGELOG.md
  README.md
  src/depends-on-method.ts
  src/endpoint.ts
  src/nesting.ts
  tests/unit/nesting.spec.ts
  tests/unit/routing.spec.ts
Labels: documentation, enhancement

#2192 Fixing the nested route traverse order — FIFO
  src/routing-walker.ts
Labels: refactoring, prevention

#2193 Drop `Endpoint::getMimeTypes()`
  CHANGELOG.md
  src/documentation-helpers.ts
  src/documentation.ts
  src/endpoint.ts
  src/integration.ts
  src/result-helpers.ts
  src/routing.ts
  tests/unit/__snapshots__/endpoint.spec.ts.snap
  tests/unit/endpoint.spec.ts
Labels: documentation, refactoring, breaking

#2195 Vitest snapshot serializers instead of traversing schema in tests
  eslint.config.js
  tests/helpers.ts
  tests/unit/documentation-helpers.spec.ts
  tests/unit/endpoint.spec.ts
  tests/unit/endpoints-factory.spec.ts
  tests/unit/io-schema.spec.ts
  vitest.setup.ts
Labels: coverage, refactoring

#2197 Upgrading all dependencies.
  yarn.lock
Labels: dependencies

#2198 Avoid logo distortion
  src/server.ts
  src/startup-logo.ts
  tests/system/system.spec.ts
  tests/unit/startup-logo.spec.ts
Labels: refactoring, prevention

#2199 Self-diagnosis disabled on production
  README.md
  src/diagnostics.ts
  src/routing.ts
Labels: refactoring, prevention

#2191 Feat: Empty response support
  CHANGELOG.md
  README.md
  example/endpoints/delete-user.ts
  example/example.client.ts
  example/example.documentation.yaml
  example/factories.ts
  example/routing.ts
  package.json
  src/api-response.ts
  src/diagnostics.ts
  src/documentation-helpers.ts
  src/integration.ts
  src/result-helpers.ts
  src/zts.ts
  tests/system/example.spec.ts
  tests/unit/__snapshots__/documentation.spec.ts.snap
  tests/unit/__snapshots__/integration.spec.ts.snap
  tests/unit/__snapshots__/zts.spec.ts.snap
Labels: enhancement, miracle

#2202 Requesting OpenAPI validation
  .github/workflows/swagger.yml
  package.json
  tests/oas/validate.spec.ts
  tsconfig.json
Labels: coverage, refactoring, external bug

#2180 Add comparison with tRPC to README
  README.md
Labels: documentation

#2208 Replacing `chain()` with `.map()`
  src/integration-helpers.ts
Labels: refactoring

#2209 Replacing `.flatMap()` with `chain()`
  eslint.config.js
  src/common-helpers.ts
  src/zts.ts
  tests/bench/experiment.bench.ts
Labels: refactoring

#2215 Organizing ESLint rules
  eslint.config.js
Labels: refactoring
