Repository RobinTail/express-zod-api, pull requests merged in 2025-04, with the labels that each got.

#2475 Drop Express 4
  .github/workflows/validations.yml
  CHANGELOG.md
  README.md
  express-zod-api/package.json
  express-zod-api/src/server-helpers.ts
  express-zod-api/tests/server-helpers.spec.ts
Labels: documentation, dependencies, breaking

#2476 Deprecating v18
  SECURITY.md
Labels: documentation

#2514 Supporting HTML forms (URL encoded)
  CHANGELOG.md
  README.md
  example/config.ts
  example/endpoints/submit-feedback.ts
  example/example.client.ts
  example/example.documentation.yaml
  example/index.spec.ts
  example/routing.ts
  express-zod-api/src/config-type.ts
  express-zod-api/src/content-type.ts
  express-zod-api/src/deep-checks.ts
  express-zod-api/src/endpoint.ts
  express-zod-api/src/form-schema.ts
  express-zod-api/src/io-schema.ts
  express-zod-api/src/proprietary-schemas.ts
  express-zod-api/src/server.ts
  express-zod-api/tests/__snapshots__/form-schema.spec.ts.snap
  express-zod-api/tests/__snapshots__/index.spec.ts.snap
  express-zod-api/tests/content-type.spec.ts
  express-zod-api/tests/endpoint.spec.ts
  express-zod-api/tests/express-mock.ts
  express-zod-api/tests/form-schema.spec.ts
  express-zod-api/tests/io-schema.spec.ts
  express-zod-api/tests/server.spec.ts
Labels: documentation, enhancement

#2515 Add contributor
  CHANGELOG.md
  README.md
Labels: documentation

#2516 Fix dead link in SECURITY.md
  SECURITY.md
Labels: documentation

#2517 Improving JSDoc
  CHANGELOG.md
  express-zod-api/src/config-type.ts
  express-zod-api/src/endpoint.ts
  express-zod-api/src/endpoints-factory.ts
  express-zod-api/src/middleware.ts
Labels: documentation

#2523 Replacing deprecated type assertions
  example/index.spec.ts
  express-zod-api/tests/documentation.spec.ts
  express-zod-api/tests/endpoints-factory.spec.ts
  express-zod-api/tests/file-schema.spec.ts
  express-zod-api/tests/index.spec.ts
  express-zod-api/tests/io-schema.spec.ts
  express-zod-api/tests/result-handler.spec.ts
  express-zod-api/tests/sse.spec.ts
Labels: coverage, refactoring

#2521 Ability to configure and disable `accessLogger`
  CHANGELOG.md
  README.md
  express-zod-api/src/config-type.ts
  express-zod-api/src/server-helpers.ts
  express-zod-api/tests/__snapshots__/server-helpers.spec.ts.snap
  express-zod-api/tests/server-helpers.spec.ts
Labels: enhancement

#2524 Removing `try..catch` in `createLoggingMiddleware`
  express-zod-api/src/server-helpers.ts
  express-zod-api/tests/__snapshots__/server-helpers.spec.ts.snap
  express-zod-api/tests/server-helpers.spec.ts
Labels: refactoring

#2527 Add `ez.form()` symbol to issue #952 test
  issue952-test/symbols.ts
Labels: coverage

#2526 Fix for `ez.raw()` without extension
  CHANGELOG.md
  express-zod-api/src/raw-schema.ts
  express-zod-api/tests/raw-schema.spec.ts
Labels: coverage, refactoring, prevention

#2528 Backport `ez.raw()` fix for v21
  CHANGELOG.md
  coverage.svg
  src/raw-schema.ts
  tests/unit/raw-schema.spec.ts
Labels: prevention

#2529 Backport `ez.raw()` fix for v20
  CHANGELOG.md
  coverage.svg
  src/raw-schema.ts
  tests/unit/raw-schema.spec.ts
Labels: prevention

#2530 Backport `ez.raw()` fix for v19
  CHANGELOG.md
  coverage.svg
  package.json
  src/raw-schema.ts
  tests/unit/raw-schema.spec.ts
Labels: prevention

#2525 Aligning catcher with documentation
  CHANGELOG.md
  README.md
  express-zod-api/src/server-helpers.ts
  express-zod-api/tests/__snapshots__/system.spec.ts.snap
  express-zod-api/tests/server-helpers.spec.ts
  express-zod-api/tests/system.spec.ts
Labels: documentation, coverage, prevention

#2532 Backport catcher alignment for v21
  CHANGELOG.md
  README.md
  src/server-helpers.ts
  tests/system/__snapshots__/system.spec.ts.snap
  tests/system/system.spec.ts
  tests/unit/server-helpers.spec.ts
Labels: prevention

#2533 Backport catcher alignment for v20
  CHANGELOG.md
  README.md
  src/server-helpers.ts
  tests/system/__snapshots__/system.spec.ts.snap
  tests/system/system.spec.ts
  tests/unit/server-helpers.spec.ts
Labels: prevention

#2534 Backport catcher alignment to v19
  CHANGELOG.md
  src/server-helpers.ts
  src/server.ts
  tests/system/__snapshots__/system.spec.ts.snap
  tests/system/system.spec.ts
  tests/unit/server-helpers.spec.ts
Labels: prevention

#2522 Using `errorHandler` from config for `testMiddleware()`
  CHANGELOG.md
  README.md
  express-zod-api/src/migration.ts
  express-zod-api/src/testing.ts
  express-zod-api/tests/__snapshots__/migration.spec.ts.snap
  express-zod-api/tests/common-helpers.spec.ts
  express-zod-api/tests/endpoints-factory.spec.ts
  express-zod-api/tests/metadata.spec.ts
  express-zod-api/tests/migration.spec.ts
  express-zod-api/tests/testing.spec.ts
  express-zod-api/tests/zod-plugin.spec.ts
  express-zod-api/vitest.setup.ts
Labels: documentation, refactoring, breaking

#2539 Requiring `express@^5.1.0`
  CHANGELOG.md
  express-zod-api/package.json
Labels: documentation, breaking

#2357 v23 is for Sonia
  .github/workflows/codeql-analysis.yml
  .github/workflows/node.js.yml
  .github/workflows/validations.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  compat-test/eslint.config.js
  compat-test/migration.spec.ts
  compat-test/sample.ts
  eslint.config.js
  express-zod-api/package.json
  express-zod-api/src/config-type.ts
  express-zod-api/src/depends-on-method.ts
  express-zod-api/src/diagnostics.ts
  express-zod-api/src/documentation.ts
  express-zod-api/src/endpoint.ts
  express-zod-api/src/index.ts
  express-zod-api/src/integration-base.ts
  express-zod-api/src/integration.ts
  express-zod-api/src/io-schema.ts
  express-zod-api/src/middleware.ts
  express-zod-api/src/migration.ts
  express-zod-api/src/result-handler.ts
  express-zod-api/src/routing-walker.ts
  express-zod-api/src/routing.ts
  express-zod-api/src/security.ts
  express-zod-api/src/serve-static.ts
  express-zod-api/src/server-helpers.ts
  express-zod-api/src/startup-logo.ts
  express-zod-api/src/testing.ts
  express-zod-api/tests/__snapshots__/documentation-helpers.spec.ts.snap
  express-zod-api/tests/__snapshots__/endpoints-factory.spec.ts.snap
  express-zod-api/tests/__snapshots__/migration.spec.ts.snap
  express-zod-api/tests/__snapshots__/server-helpers.spec.ts.snap
  express-zod-api/tests/common-helpers.spec.ts
  express-zod-api/tests/documentation-helpers.spec.ts
  express-zod-api/tests/endpoint.spec.ts
  express-zod-api/tests/endpoints-factory.spec.ts
  express-zod-api/tests/index.spec.ts
  express-zod-api/tests/metadata.spec.ts
  express-zod-api/tests/middleware.spec.ts
  express-zod-api/tests/migration.spec.ts
  express-zod-api/tests/serve-static.spec.ts
  express-zod-api/tests/server-helpers.spec.ts
  express-zod-api/tests/system.spec.ts
  express-zod-api/tests/testing.spec.ts
  express-zod-api/tests/zod-plugin.spec.ts
  express-zod-api/tsconfig.json
  express-zod-api/vitest.setup.ts
  package.json
  yarn.lock
Labels: dependencies, refactoring, CI/CD, breaking, dedication

#2543 Feat: Depicting arrays having fixed length
  CHANGELOG.md
  express-zod-api/src/documentation-helpers.ts
  express-zod-api/tests/__snapshots__/documentation-helpers.spec.ts.snap
  express-zod-api/tests/documentation-helpers.spec.ts
Labels: enhancement

#2545 Depicting `propertyNames` for `z.record()`
  CHANGELOG.md
  example/example.documentation.yaml
  express-zod-api/src/documentation-helpers.ts
  express-zod-api/tests/__snapshots__/documentation-helpers.spec.ts.snap
  express-zod-api/tests/__snapshots__/documentation.spec.ts.snap
  express-zod-api/tests/documentation-helpers.spec.ts
Labels: enhancement

#2549 Moving `deprecated` to the top level of global registry
  express-zod-api/src/documentation-helpers.ts
  express-zod-api/src/metadata.ts
  express-zod-api/src/zod-plugin.ts
  express-zod-api/src/zts.ts
  express-zod-api/tests/zod-plugin.spec.ts
Labels: refactoring

#2551 Fix 'actually nullable' logic in `onEach`
  CHANGELOG.md
  express-zod-api/src/documentation-helpers.ts
  express-zod-api/tests/__snapshots__/documentation-helpers.spec.ts.snap
  express-zod-api/tests/__snapshots__/documentation.spec.ts.snap
Labels: prevention

#2552 Fix optionals in response
  CHANGELOG.md
  express-zod-api/src/common-helpers.ts
  express-zod-api/src/documentation-helpers.ts
  express-zod-api/src/zts.ts
  express-zod-api/tests/__snapshots__/documentation.spec.ts.snap
  express-zod-api/tests/common-helpers.spec.ts
Labels: prevention

#2547 Delegating depiction to Zod 4
  CHANGELOG.md
  README.md
  example/example.documentation.yaml
  express-zod-api/src/common-helpers.ts
  express-zod-api/src/documentation-helpers.ts
  express-zod-api/src/documentation.ts
  express-zod-api/src/index.ts
  express-zod-api/tests/__snapshots__/documentation-helpers.spec.ts.snap
  express-zod-api/tests/__snapshots__/documentation.spec.ts.snap
  express-zod-api/tests/documentation-helpers.spec.ts
  express-zod-api/tests/documentation.spec.ts
  express-zod-api/tests/index.spec.ts
Labels: documentation, refactoring, breaking, external bug

#2553 Helper to ensure valid `type`
  express-zod-api/src/documentation-helpers.ts
Labels: enhancement, refactoring

#2554 Backporting improved `getSupportedType`
  express-zod-api/src/documentation-helpers.ts
Labels: refactoring

#2557 Removing overrides for enums and literals
  example/example.documentation.yaml
  express-zod-api/src/documentation-helpers.ts
  express-zod-api/tests/__snapshots__/documentation-helpers.spec.ts.snap
  express-zod-api/tests/__snapshots__/documentation.spec.ts.snap
Labels: refactoring

#2559 Removing overrides for `any`
  example/example.documentation.yaml
  express-zod-api/src/documentation-helpers.ts
  express-zod-api/tests/__snapshots__/documentation-helpers.spec.ts.snap
  express-zod-api/tests/__snapshots__/documentation.spec.ts.snap
Labels: refactoring

#2556 Tests for overriders and minor adjustments
  express-zod-api/src/documentation-helpers.ts
  express-zod-api/tests/__snapshots__/documentation-helpers.spec.ts.snap
  express-zod-api/tests/__snapshots__/documentation.spec.ts.snap
  express-zod-api/tests/documentation-helpers.spec.ts
  express-zod-api/tests/env.spec.ts
Labels: coverage, refactoring

#2560 Support `ZodInterface`
  express-zod-api/src/io-schema.ts
  express-zod-api/src/zts-helpers.ts
  express-zod-api/src/zts.ts
  express-zod-api/tests/__snapshots__/documentation.spec.ts.snap
  express-zod-api/tests/__snapshots__/integration.spec.ts.snap
  express-zod-api/tests/__snapshots__/io-schema.spec.ts.snap
  express-zod-api/tests/__snapshots__/zts.spec.ts.snap
  express-zod-api/tests/documentation.spec.ts
  express-zod-api/tests/env.spec.ts
  express-zod-api/tests/integration.spec.ts
  express-zod-api/tests/io-schema.spec.ts
  express-zod-api/tests/zts.spec.ts
Labels: enhancement

#2561 Drop `optionalPropStyle` from `Integration`
  CHANGELOG.md
  README.md
  express-zod-api/src/integration.ts
  express-zod-api/src/zts-helpers.ts
  express-zod-api/src/zts.ts
  express-zod-api/tests/__snapshots__/integration.spec.ts.snap
  express-zod-api/tests/integration.spec.ts
  express-zod-api/tests/zts.spec.ts
Labels: documentation, refactoring, breaking

#2564 Brand is the only the metadata that withstands refinements
  CHANGELOG.md
  express-zod-api/src/zod-plugin.ts
  express-zod-api/tests/zod-plugin.spec.ts
Labels: refactoring

#2565 Metadata preservation fix
  express-zod-api/src/io-schema.ts
  express-zod-api/src/metadata.ts
  express-zod-api/src/zod-plugin.ts
  express-zod-api/tests/metadata.spec.ts
Labels: refactoring, prevention

#2567 Changing the type of internal examples to `z.$input` symbol
  express-zod-api/src/metadata.ts
Labels: enhancement

#2573 Improve handling of `ZodError` by `ensureError`
  express-zod-api/src/common-helpers.ts
  express-zod-api/tests/__snapshots__/system.spec.ts.snap
  express-zod-api/tests/common-helpers.spec.ts
Labels: refactoring

#2578 Removing deprecated alias `ZodTypeAny`
  express-zod-api/src/api-response.ts
  express-zod-api/src/integration.ts
  express-zod-api/src/result-handler.ts
  express-zod-api/src/sse.ts
  express-zod-api/src/zts.ts
  express-zod-api/tests/index.spec.ts
  express-zod-api/tests/integration.spec.ts
Labels: refactoring

#2579 Migrating traverse related methods to core types
  express-zod-api/src/common-helpers.ts
  express-zod-api/src/documentation-helpers.ts
  express-zod-api/src/zts.ts
Labels: refactoring

#2580 Replacing `instanceof` in traverse
  express-zod-api/src/common-helpers.ts
  express-zod-api/src/documentation-helpers.ts
  express-zod-api/src/zts.ts
Labels: enhancement, refactoring

#2581 Implementing `unref()` helper
  express-zod-api/src/documentation-helpers.ts
  express-zod-api/tests/documentation-helpers.spec.ts
Labels: enhancement, refactoring, external bug

#2582 Schema compliance adjustment
  example/example.documentation.yaml
  express-zod-api/src/documentation-helpers.ts
  express-zod-api/tests/__snapshots__/documentation.spec.ts.snap
Labels: refactoring

#2583 Restoring immutable depicters
  CHANGELOG.md
  README.md
  express-zod-api/src/documentation-helpers.ts
  express-zod-api/src/index.ts
  express-zod-api/tests/documentation-helpers.spec.ts
  express-zod-api/tests/documentation.spec.ts
  express-zod-api/tests/index.spec.ts
Labels: documentation, enhancement, refactoring

#2584 Coerce became safer
  README.md
  express-zod-api/tests/env.spec.ts
Labels: documentation

#2585 Reset migration for v24
  compat-test/eslint.config.js
  compat-test/migration.spec.ts
  express-zod-api/src/migration.ts
  express-zod-api/tests/__snapshots__/migration.spec.ts.snap
  express-zod-api/tests/migration.spec.ts
Labels: CI/CD

#2586 Migration rules for v24
  compat-test/migration.spec.ts
  compat-test/sample.ts
  express-zod-api/src/migration.ts
  express-zod-api/tests/__snapshots__/migration.spec.ts.snap
  express-zod-api/tests/migration.spec.ts
Labels: enhancement, breaking

#2590 Fix: avoid double raw check by Documentation
  express-zod-api/src/documentation-helpers.ts
  express-zod-api/tests/documentation-helpers.spec.ts
Labels: refactoring

#2589 Deep checks using `toJSONSchema`
  express-zod-api/src/deep-checks.ts
  express-zod-api/src/diagnostics.ts
  express-zod-api/src/endpoint.ts
  express-zod-api/src/errors.ts
  express-zod-api/tests/deep-checks.spec.ts
  express-zod-api/tests/errors.spec.ts
  express-zod-api/tests/routing.spec.ts
Labels: enhancement, refactoring

#2593 Fix nullable literals and enums
  example/example.documentation.yaml
  express-zod-api/src/documentation-helpers.ts
  express-zod-api/tests/__snapshots__/documentation-helpers.spec.ts.snap
  express-zod-api/tests/__snapshots__/documentation.spec.ts.snap
  express-zod-api/tests/documentation-helpers.spec.ts
  express-zod-api/tests/documentation.spec.ts
Labels: refactoring, prevention

#2594 Discriminating `ResultHandler::handler()` params
  example/factories.ts
  express-zod-api/src/endpoint.ts
  express-zod-api/src/result-handler.ts
  express-zod-api/src/result-helpers.ts
  express-zod-api/tests/result-handler.spec.ts
  express-zod-api/tests/sse.spec.ts
Labels: enhancement, refactoring
