Repository RobinTail/express-zod-api, pull requests merged in 2025-09, with the labels that each got.

#2952 Upgrading some dependencies
  package.json
  pnpm-lock.yaml
Labels: dependencies

#2955 Port for v25: avoid using `example` method in sources
  CHANGELOG.md
  README.md
  eslint.config.js
  express-zod-api/src/result-handler.ts
Labels: prevention

#2965 SSE abort signal
  express-zod-api/src/sse.ts
  express-zod-api/tests/sse.spec.ts
Labels: enhancement

#2966 feat: `AbortSignal` for SSE
  CHANGELOG.md
  README.md
  express-zod-api/package.json
  express-zod-api/src/sse.ts
  express-zod-api/tests/sse.spec.ts
Labels: enhancement

#2934 Renaming `options` to `ctx`
  CHANGELOG.md
  README.md
  dataflow.svg
  example/endpoints/retrieve-user.ts
  example/endpoints/time-subscription.ts
  example/endpoints/update-user.ts
  express-zod-api/src/endpoint.ts
  express-zod-api/src/endpoints-factory.ts
  express-zod-api/src/middleware.ts
  express-zod-api/src/result-handler.ts
  express-zod-api/src/server-helpers.ts
  express-zod-api/src/testing.ts
  express-zod-api/tests/endpoint.spec.ts
  express-zod-api/tests/endpoints-factory.spec.ts
  express-zod-api/tests/middleware.spec.ts
  express-zod-api/tests/result-handler.spec.ts
  express-zod-api/tests/routing.spec.ts
  express-zod-api/tests/sse.spec.ts
  express-zod-api/tests/system.spec.ts
  express-zod-api/tests/testing.spec.ts
  migration/index.spec.ts
  migration/index.ts
Labels: documentation, refactoring, breaking

#2912 Add missing Node engine restrictions to `zod-plugin`
  zod-plugin/CHANGELOG.md
  zod-plugin/package.json
Labels: breaking, prevention

#2971 Add `z.function()` to the list of JSON incompatible schemas
  CHANGELOG.md
  express-zod-api/src/deep-checks.ts
  express-zod-api/tests/routing.spec.ts
Labels: prevention

#2970 rm braces from `findNestedSchema`
  express-zod-api/src/deep-checks.ts
Labels: refactoring

#2972 Enabling `noUncheckedSideEffectImports` globally
  tsconfig.json
Labels: CI/CD
